# NmyPy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
conda install numpy

In [1]:
pip list

Package                       Version
----------------------------- --------------------
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
anaconda-client               1.9.0
anaconda-navigator            2.1.4
anaconda-project              0.10.2
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.2
astroid                       2.6.6
astropy                       5.0.4
asttokens                     2.0.5
async-timeout                 4.0.1
atomicwrites                  1.4.0
attrs                         21.4.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.0
bea

In [2]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Raj\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.14.0               |   py39haa95532_0         937 KB
    ------------------------------------------------------------
                                           Total:         937 KB

The following packages will be UPDATED:

  conda                               4.12.0-py39haa95532_0 --> 4.14.0-py39haa95532_0




conda-4.14.0         | 937 KB    |            |   0% 
conda-4.14.0         | 937 KB    | 1          |   2% 
conda-4.14.0         | 937 KB    | 3          |   3% 
conda-4.14.0         | 937 KB    | 5          |   5% 
conda-4.14.0         | 937 KB    | 6          |   7% 
conda-4.14.0         | 937 KB    | 8          |   9% 
conda-4.14.0         | 937 KB    | #          |  10% 
con

In [4]:
import numpy as np

In [5]:
print(np.__version__)

##to check version of numpy

1.21.5


In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [25]:
print(np.amin(arr)) ##min value
print(np.amax(arr)) ##max value
print(np.mean(arr))  ##mean value of data set
print(np.median(arr)) 
print(np.ptp(arr))##range of value along with an axis(peak to peak)
print(np.std(arr)) ##standard deviation
print(np.var(arr)) ##variance   v=a^2//((standard deviation)^2)
print(np.average(arr))  ##for avg
print(np.percentile(arr,55)) ##for percentile







1
10
5.5
5.5
9
2.8722813232690143
8.25
5.5
5.95


In [28]:

#create simple array from the list
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
#dianmension of the arry

print(arr.ndim)


2


In [30]:
#shape of the array

print(arr.shape)

(2, 4)


In [31]:
#to find data location

print(arr.data)

## Random Number Generator Using Numpy 

In [37]:
from numpy import random
x = random.randint(100)
print(x)


96


In [38]:
from numpy import random
x = random.randint(100)
print(x)


88


In [39]:
from numpy import random
x = random.randint(100)
print(x)


10


In [40]:
from numpy import random
x = random.randint(10)
print(x)


2


In [41]:
from numpy import random
x = random.randint()
print(x)


TypeError: randint() takes at least 1 positional argument (0 given)

In [43]:
from numpy import random   ##to generate random float value
x = random.rand()
print(x)


0.8314965618864514


In [45]:
from numpy import random  ##generate random array
x = random.randint(100,size=(5))
print(x)


[42 11 22 82 30]


In [46]:
from numpy import random  ##generate random array
x = random.randint(100,size=(5))
print(x)

[46  0 12  8 22]


In [50]:
##Generate a 2-D array eith 3 rows ,each contain 5 ramdom int value

from numpy import random  
x = random.randint(100,size=(3,5))
print(x)


[[81 26 71 88 44]
 [13 26 50 74 89]
 [ 7 44 13  4 55]]


In [1]:
from numpy import random  ##ramdom value will not change
random.seed(101) 
x = random.randint(100,size=(3,5))
print(x)


[[95 11 81 70 63]
 [87 75  9 77 40]
 [ 4 63 40 60 92]]


In [2]:
from numpy import random  
random.seed(101)
x = random.randint(100,size=(3,5))
print(x)

[[95 11 81 70 63]
 [87 75  9 77 40]
 [ 4 63 40 60 92]]


In [5]:
import numpy as np

#creating 1-D list
list1 = [1,2,3]

#creating 1-D list vertical

list2 = [[10],
        [20],
        [30]]


#create vector1

vector1 = np.array(list1)
vector2 = np.array(list2)

print("horizontal vector")
print(vector1)

print("...........................")

print("vertical vector")
print(vector2)



horizontal vector
[1 2 3]
...........................
vertical vector
[[10]
 [20]
 [30]]


In [6]:
a=np.matrix("1 2;3 4")
print(a)

[[1 2]
 [3 4]]


In [9]:
#array like input
b=np.matrix([[1,2,3],[5,4]])
b


matrix([[list([1, 2, 3]), list([5, 4])]], dtype=object)

In [1]:
import numpy as np

In [3]:
a = 5
b = [[6,7],[1,2]]


print(np.dot(a,b))

[[30 35]
 [ 5 10]]


In [8]:
a = [[5,2],
     [2,2]]

b = [[1,2],
     [10,2]]

print(np.dot(a,b))
print(".....................")
print(np.dot(b,a))

[[25 14]
 [22  8]]
.....................
[[ 9  6]
 [54 24]]


In [15]:
import numpy as np

a = ([5,2], [2,2])

np.transpose(a)


array([[5, 2],
       [2, 2]])

In [1]:
import numpy as np


# Percentile & interquartile in NUmpy

In [2]:
import numpy as np


In [7]:
data=[32,11,25,45,12,55,56,78,99,44,55,55,46,78,79,26,66,56,63,65]

#first quartile(Q1)
##a+b/2 middle value
Q1=np.median(data[:10])
print(Q1)


#thrid quartile(Q3)

Q3=np.median(data[10:])
print(Q3)

##interquartile range

IQR=Q3-Q1
print(IQR)

44.5
59.5
15.0


# Array Brodcasting in Numpy

In [9]:
a = np.array([1.0,2.0,3.0])
b = np.array([2.0,2.0,2.0])

a*b

array([2., 4., 6.])

In [10]:
a = np.array([1.0,2.0,3.0])
b = 2.0

a*b

array([2., 4., 6.])

# Calculate BMI of Cricket Players

In [11]:
#heights of players

In [14]:
hg_in=[61,65,64,69,70,68,64,63,62,66,72]

#convert into numpy array

ht_np=np.array(hg_in)

#conver height from inch to meter by exposing it to 0.0245

ht_np = ht_np*0.0245

ht_np

array([1.4945, 1.5925, 1.568 , 1.6905, 1.715 , 1.666 , 1.568 , 1.5435,
       1.519 , 1.617 , 1.764 ])

In [15]:
#weight of players in pound

wt_pd = [100,200,160,180,140,155,165,172,180,200,168]

#convert into numpy array

wt_np=np.array(wt_pd)

#conver weight from pound to kg by exposing it to 0.45

wt_np = wt_np*0.45


wt_np

array([45.  , 90.  , 72.  , 81.  , 63.  , 69.75, 74.25, 77.4 , 81.  ,
       90.  , 75.6 ])

In [16]:
#BMI calculation

BMI= wt_np/(ht_np**2)
BMI

array([20.1474773 , 35.48817184, 29.28467305, 28.3435777 , 21.41964658,
       25.13010006, 30.19981909, 32.48835283, 35.10503991, 34.42091966,
       24.29543246])

In [17]:
BMI[-1]

24.295432458697764

In [18]:
BMI[BMI<21]

array([20.1474773])

In [19]:
BMI[:5]

array([20.1474773 , 35.48817184, 29.28467305, 28.3435777 , 21.41964658])

#making 2d array of players

In [21]:
players = np.array([wt_np,ht_np])
players


array([[45.    , 90.    , 72.    , 81.    , 63.    , 69.75  , 74.25  ,
        77.4   , 81.    , 90.    , 75.6   ],
       [ 1.4945,  1.5925,  1.568 ,  1.6905,  1.715 ,  1.666 ,  1.568 ,
         1.5435,  1.519 ,  1.617 ,  1.764 ]])

In [22]:
players[0][2]

72.0

In [23]:
players[1][2]

1.568

In [24]:
players[1]

array([1.4945, 1.5925, 1.568 , 1.6905, 1.715 , 1.666 , 1.568 , 1.5435,
       1.519 , 1.617 , 1.764 ])

In [28]:
#transpose

pT=players.transpose()
print(pT.shape)

print("---------------------------------")
print(pT)

(11, 2)
---------------------------------
[[45.      1.4945]
 [90.      1.5925]
 [72.      1.568 ]
 [81.      1.6905]
 [63.      1.715 ]
 [69.75    1.666 ]
 [74.25    1.568 ]
 [77.4     1.5435]
 [81.      1.519 ]
 [90.      1.617 ]
 [75.6     1.764 ]]


In [31]:
#stastical and mathematcal function on players data

print(np.mean(wt_np))

print(np.median(wt_np))

print(np.sum(wt_np))


#standard deviation

print(np.std(wt_np))


#corelation cofficient
print(np.corrcoef(wt_np,ht_np))


74.45454545454545
75.60000000000001
819.0
12.082941667443528
[[1.         0.16451886]
 [0.16451886 1.        ]]


In [1]:
import numpy as np

In [2]:
length=[10,20,30,40,50,60,70,80,90,100]
length_array=np.array(length)
length_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [4]:
breadth=[10,20,30,40,50,60,70,80,90,100]
breadth_array=np.array(breadth)
breadth_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [7]:
area=length_array*breadth_array
area

array([  100,   400,   900,  1600,  2500,  3600,  4900,  6400,  8100,
       10000])